echo "          Extracting table GFPF"
cp $PRECISION100_EXECUTION_CONTAINER_FOLDER/$CONTAINER/GFPF.dat $PRECISION100_OPERATOR_SMART_LOADER_INPUT_FOLDER
sleep $SIMULATION_SLEEP;
echo "          Extracting table SCPF"
cp $PRECISION100_EXECUTION_CONTAINER_FOLDER/$CONTAINER/SCPF.dat $PRECISION100_OPERATOR_SMART_LOADER_INPUT_FOLDER
sleep $SIMULATION_SLEEP;
echo "          Extracting table C8PF"
cp $PRECISION100_EXECUTION_CONTAINER_FOLDER/$CONTAINER/C8PF.dat $PRECISION100_OPERATOR_SMART_LOADER_INPUT_FOLDER
sleep $SIMULATION_SLEEP;
echo "          Extracting table S5PF"
cp $PRECISION100_EXECUTION_CONTAINER_FOLDER/$CONTAINER/S5PF.dat $PRECISION100_OPERATOR_SMART_LOADER_INPUT_FOLDER
sleep $SIMULATION_SLEEP;
echo "          Extracting table C5PF"
cp $PRECISION100_EXECUTION_CONTAINER_FOLDER/$CONTAINER/C5PF.dat $PRECISION100_OPERATOR_SMART_LOADER_INPUT_FOLDER
sleep $SIMULATION_SLEEP;
echo "          Extracting table SX20LF"
cp $PRECISION100_EXECUTION_CONTAINER_FOLDER/$CONTAINER/SX20LF.dat $PRECISION100_OPERATOR_SMART_LOADER_INPUT_FOLDER
sleep $SIMULATION_SLEEP;
echo "          Extracting table SVPF"
cp $PRECISION100_EXECUTION_CONTAINER_FOLDER/$CONTAINER/SVPF.dat $PRECISION100_OPERATOR_SMART_LOADER_INPUT_FOLDER
sleep $SIMULATION_SLEEP;
echo "          Extracting table BGPF"
cp $PRECISION100_EXECUTION_CONTAINER_FOLDER/$CONTAINER/BGPF.dat $PRECISION100_OPERATOR_SMART_LOADER_INPUT_FOLDER
sleep $SIMULATION_SLEEP;
echo "          Extracting table RIPF"
cp $PRECISION100_EXECUTION_CONTAINER_FOLDER/$CONTAINER/RIPF.dat $PRECISION100_OPERATOR_SMART_LOADER_INPUT_FOLDER
sleep $SIMULATION_SLEEP;
echo "          Extracting table RJPF"
cp $PRECISION100_EXECUTION_CONTAINER_FOLDER/$CONTAINER/RJPF.dat $PRECISION100_OPERATOR_SMART_LOADER_INPUT_FOLDER
sleep $SIMULATION_SLEEP;
